# Generated by Django 5.2.8 on 2025-12-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
        migrations.DeleteModel(
            name='TechTool',
        ),
    ]
