# Generated by Django 5.2.8 on 2025-12-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='category',
        ),
    ]
