# Generated by Django 5.2.8 on 2025-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
