# Generated by Django 5.2.8 on 2025-12-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
