# Generated by Django 5.2.8 on 2025-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Sent', 'Sent')], default='Draft', max_length=15),
        ),
    ]
