# Generated by Django 5.2.8 on 2025-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('skills', models.ManyToManyField(related_name='categories', to='portfolio.techtool')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('live_link', models.URLField()),
                ('role', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('tech_stack', models.ManyToManyField(related_name='projects', to='portfolio.techtool')),
                ('tools', models.ManyToManyField(blank=True, related_name='tool_projects', to='portfolio.techtool')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(related_name='experiences', to='portfolio.techtool')),
            ],
        ),
    ]
